# Generated by Django 5.0.2 on 2024-02-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_app_secret_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
